'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cul_pro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12935130_df48_m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12935130_df48_m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16956712_Samurai_silhouette_in_Asian_Landscape__Stock_Vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16956712-Samurai-silhouette-in-Asian-Landscape--Stock-Vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3839665_medieval_knight_by_lijinbo78() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3839665-medieval_knight_by_lijinbo78", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3839665_medieval_knight_by_lijinbo781() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3839665-medieval_knight_by_lijinbo781", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _59_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("59_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _59_big1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("59_big1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6144_256x256x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6144-256x256x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9iz664diE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9iz664diE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9iz664diE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9iz664diE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9iz664diE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9iz664diE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9iz664diE3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9iz664diE3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancient_interviewing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancient_interviewing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancient_interviewing1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancient_interviewing1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property angry_bird_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("angry bird right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property angry_bird_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("angry bird up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property angrybird_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("angrybird down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property angrybird_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("angrybird left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AW9YjSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AW9YjSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background_mario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background mario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property catapult_clipart_schleuder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catapult-clipart-schleuder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property catapult_clipart_schleuder1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catapult-clipart-schleuder1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property catapult_clipart_schleuder2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catapult-clipart-schleuder2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1___22x22_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1) (22x22)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (1)3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__3___19x16_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (3) (19x16)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download__3_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download (3)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fertyyt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fertyyt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fertyyt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fertyyt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fred_Flintstone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fred_Flintstone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fred1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fred1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fred11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fred11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fred1right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fred1right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Introduction() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Introduction", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property knighthead() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("knighthead", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property llllllllllllllllllll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("llllllllllllllllllll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mariobonus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mariobonus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marioface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marioface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maze1block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maze1block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maze1blockup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maze1blockup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maze3block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maze3block", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maze3blockup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maze3blockup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mmmmmmm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mmmmmmm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pb07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pb07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property picnote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picnote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property resembling_the_surface_of_a_wooden_wall_paneling_foc1gs459wrmvo9d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resembling-the-surface-of-a-wooden-wall-paneling-foc1gs459wrmvo9d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property resembling_the_surface_of_a_wooden_wall_paneling_foc1gs459wrmvo9d1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resembling-the-surface-of-a-wooden-wall-paneling-foc1gs459wrmvo9d1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sadfg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sadfg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property score() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("score", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property score1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("score1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property score2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("score2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_03_16_at_09_02_PM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-03-16 at 09.02 PM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_02_14_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 02.14 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_02_17_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 02.17 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_03_08_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 03.08 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_03_20_PM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 03.20 PM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_04_15_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 04.15 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_07_21_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 07.21 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_22_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.22 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_26_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.26 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_28_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.28 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_35_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.35 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_43_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.43 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_08_46_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 08.46 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_081() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 081", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_09_02_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 09.02 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_09_17_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 09.17 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_19_16_at_12_57_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-19-16 at 12.57 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_01_13_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 01.13 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_01_19_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 01.19 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_40_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.40 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_40_AM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.40 AM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_44_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.44 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_44_AM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.44 AM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_47_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.47 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_47_AM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.47 AM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_48_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.48 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_20_16_at_12_48_AM_001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-20-16 at 12.48 AM 001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_09_41_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 09.41 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_10_58_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 10.58 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_10_59_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 10.59 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_11_28_AM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 11.28 AM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screen_Shot_01_21_16_at_12_21_PM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screen Shot 01-21-16 at 12.21 PM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snow_character1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow character1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock_vector_cartoon_brick_wall_79588576() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-vector-cartoon-brick-wall-79588576", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property super_mario_wallpaper_by_desidus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("super_mario_wallpaper_by_desidus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unnamed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unnamed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_1ghfy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-1ghfy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vvvvvvv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vvvvvvv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property www() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("www", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
